#version: '3.8'

services:
  # Banco de Dados
  database:
    image: postgres:15-alpine
    container_name: infra_postgres
    environment:
      POSTGRES_USER: infra_user
      POSTGRES_PASSWORD: my_infra_password
      POSTGRES_DB: db_infra
    volumes:
      - postgresql_dbase:/var/lib/postgresql/data
    networks:
      - infra_network

  # Frontend (usa o Dockerfile da sua foto)
  frontend:
    build:
      context: ./front1
      #dockerfile: Dockerfile
    container_name: infra_frontend
    # Não expomos a porta para o seu PC, apenas para a rede interna
    networks:
      - infra_network
    depends_on:
      - database

  # Backend
  backend:
    build:
      context: ./back1
      *dockerfile: Dockerfile
    container_name: infra_backend
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/meu_banco
    networks:
      - infra_network
    depends_on:
      - database

  # Nginx - A Única Porta de Entrada do usuário
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: infra_nginx_proxy
    ports:
      - "80:80" # Expõe a porta 80 para a sua máquina local
    networks:
      - infra_network
    depends_on:
      - frontend
      - backend

networks:
  infra_network:
    driver: bridge

volumes:
  postgresql_dbase:
