# nginx/default.conf

upstream frontend_server {
    server frontend:80;
}

upstream backend_server {
    server backend:3000;
}

# 1. BLOCO HTTP (Porta 80) - Redireciona tudo para HTTPS
server {
    listen 80;
    server_name cvh.duckdns.or www.cvh.duckdns.org.com;

    # Rota obrigatória para a validação inicial do Certbot (ACME Challenge)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redireciona todas as outras requisições HTTP para HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. BLOCO HTTPS (Porta 443) - Onde a mágica segura acontece
server {
    listen 443 ssl;
    server_name cvh.duckdns.org www.duckdns.org.com;

    # Caminho dos certificados (que o Certbot vai gerar dentro do volume)
    ssl_certificate /etc/letsencrypt/live/www.duckdns.org.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.duckdns.org.com/privkey.pem;

    # Configurações de segurança recomendadas para SSL (Modernas)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Logs
    access_log /var/log/nginx/secure_access.log;
    error_log /var/log/nginx/secure_error.log;

    # Proxy para o Backend
    location /api/ {
        proxy_pass http://back1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy para o Frontend
    location / {
        proxy_pass http://front1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
