name: Teste Workflow

on:
  push:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Teste
        run: |
          echo "Workflow funcionando"
          pwd
          ls -la
